// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AssemblyLoadDebugger
{
    static class Vsix
    {
        public const string Id = "34f00824-cb6a-4bc1-a27d-7375239cdd2f";
        public const string Name = "Assembly Load Debugger";
        public const string Description = @"Shows what assemblies Visual Studio loads and what component caused it to load";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mike Lorbetske";
        public const string Tags = "assembly, performance, extensions";
    }
}
