// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AssemblyLoadDebugger
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidAssemblyLoadDebuggerPackageString = "b2195adc-e364-4d6e-9d08-74b500b223f4";
        public const string guidAssemblyLoadDebuggerPackageCmdSetString = "852872c5-92a2-4343-9bdd-ffd69e03f226";
        public static Guid guidAssemblyLoadDebuggerPackage = new Guid(guidAssemblyLoadDebuggerPackageString);
        public static Guid guidAssemblyLoadDebuggerPackageCmdSet = new Guid(guidAssemblyLoadDebuggerPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int AssemblyLoadDebuggerCommandId = 0x0100;
    }
}
